#!/usr/bin/env python3
import os, psutil, shelve as sh, sys
from subprocess import call
if __name__ == '__main__':
    try:
        db = sh.open('/opt/SA_stats/compDB.db', writeback=True)
        killList = db['PIDs']
    except FileNotFoundError:
        print('"compDB.db" not found')
        sys.exit()        
    for component in db['components']: 
        print(db['components'][component]['PID'])
        try:
            psutil.Process(db['components'][component]['PID']).kill()            
        except psutil.NoSuchProcess:
            print('component-process not found')
        call(['/opt/httpComponent/send_trace.o', str(db['components'][component]['PID']), '0'])
        call('amfpm --stop'.split(' '))
    db['components'] = {}
    db['PIDs'] = []
    db.close()
    #os.remove('/opt/SA_stats/compDB.db')