#!/usr/bin/env python3
import os, psutil, shelve as sh, sys
from subprocess import call
if __name__ == '__main__':
    try:
        db = sh.open('/opt/SA_stats/compDB.db', writeback=True)
        killList = db['PIDs']
    except FileNotFoundError:
        print('"compDB.db" not found')
        sys.exit()        
    for component in db['components']: 
        print(db['components'][component]['PID'])
        call('amfpm --stop -p'.split(' ')+ [str(db['components'][component]['PID']), component])
        try:
        	psutil.Process(db['components'][component]['PID']).terminate()            
        except psutil.NoSuchProcess:
            print('component-process not found')
        call(['/opt/httpComponent/send_trace.o', str(db['components'][component]['PID']), '0'])
    db['components'] = {}
    db['PIDs'] = []
    db.close()
    #killing all other potentially rogue http component server processes
    for p in psutil.process_iter():
        if p.name=='httpCompServer_py':
            p.terminate()
    #os.remove('/opt/SA_stats/compDB.db')